# Generated by Django 3.2 on 2024-01-19 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_user_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(default=6, max_length=20, verbose_name='Номера телефона пользователя'),
            preserve_default=False,
        ),
    ]
