# Generated by Django 3.2 on 2024-01-20 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='название организации', max_length=200, verbose_name='название')),
                ('description', models.TextField(help_text='описание организации', verbose_name='описание')),
                ('image', models.ImageField(help_text='добавьте изображение', upload_to='events/', verbose_name='изображение')),
                ('date', models.DateTimeField(help_text='выберите дату и время мероприятия')),
                ('organizations', models.ManyToManyField(help_text='выберите организации', to='organizations.Organization')),
            ],
            options={
                'verbose_name': 'мероприятие',
                'verbose_name_plural': 'мероприятия',
            },
        ),
    ]
