version: '3.9'

services:
  event_planner:
    build: .
    restart: always
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/
    ports:
     - "8000:8000"
    env_file:
      - ./.env


volumes:
  static_value:
  media_value: