version: '3.9'

services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - ./redisdata:/data

  event_planner:
    build: .
    restart: always
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/
    ports:
     - "8000:8000"
    depends_on:
      - redis
    env_file:
      - ./.env


volumes:
  static_value:
  media_value: